### PR TITLE
Add PipePluggable#canBeConnected

### PR DESCRIPTION
**Pull request by afdw**

### CODE REVIEW

**Comment by AlexIIL** [comment]
What is this used for?

**Comment by afdw** [comment]
For my fix of https://github.com/BuildCraft/BuildCraft/issues/3482

**Comment by AlexIIL** [comment]
oh ok - then it should probably be named "canBeConnectedTo" (same as block method, ideally with javadoc pointing to it but that's less important)

**Comment by afdw** [comment]
But then it will be strange, because in original method was arguments which indicated `pos` and `side`, but here they are not needed, it will be just `canBeConnectedTo()`, which looks strange. What do you think?

**Comment by AlexIIL** [comment]
Perhaps add javadoc instead pointing to the block method instead then.

**Comment by AlexIIL** [comment]
Either way this is fine.

**Comment by afdw** [comment]
You'll add javadoc yourself? Or I should send another PR? Or what?

**Comment by AlexIIL** [comment]
I've added it in https://github.com/BuildCraft/BuildCraftAPI/commit/ab177361170c89402bc2be9a11a39c3fb36d862d

**Pull request merged**
