### PR TITLE
Fixed gradle to build reobfjar properly in 8.0.x 1.9 branch

### PR DESCRIPTION
**Pull request by Craiel**

### CODE REVIEW

**Comment by AlexIIL** [comment]
Thanks!

**Comment by liach** [comment]
Why was 1.9 branch removed?

**Comment by AlexIIL** [comment]
Because it was renamed to 8.0.x.

**Comment by liach** [comment]
But that branch is for mc 1.9.4.

**Comment by AlexIIL** [comment]
Buildcraft is most likely going to be skipping the 1.9.x MC versions in favour of 1.10.2, and it makes more sense to name the branch off of the BC version than the MC version.

**Comment by liach** [comment]
Then could you make an update like [this](https://github.com/liachmodded/BuildCraftAPI/commit/8fd77fb65a5522625d844b6f05838f85fcc4b182)? I need it for compiling Railcraft.

**Comment by AlexIIL** [comment]
Unfortunately I won't be at my dev environment until Friday, but it will be updated then.

**Comment by CovertJaguar** [comment]
@liach It's only like three lines of code that need tweaking, and I just pulled the BC API into my repo earlier today anyway. You should be able to compile Railcraft now without any issues.

I'd eventually prefer to just pull in an ivy dependency like I was in 1.7.

**Pull request merged**
